name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CALDAV_BASE_URL: ${{ secrets.CALDAV_BASE_URL }}
      CALDAV_USERNAME: ${{ secrets.CALDAV_USERNAME }}
      CALDAV_PASSWORD: ${{ secrets.CALDAV_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npx jest tests/client.test.ts \
                   tests/recurrence.test.ts \
                   tests/timezone.test.ts \
                   tests/alarms.test.ts \
                   tests/description-encoding.test.ts \
                   tests/cache.test.ts \
                   tests/todos.test.ts
